using System;

namespace Seemplest.Core.DataAccess.Attributes
{
    /// <summary>
    /// This attribute marks a property as one representing an automatically generated value
    /// when inserting into the database.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class AutoGeneratedAttribute : ImoAttributeBase
    {
    }
}