//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeemplestCloud.WebClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeemplestCloud.WebClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előfizetek &amp;raquo;.
        /// </summary>
        public static string Gen_GetStarted {
            get {
                return ResourceManager.GetString("Gen_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to További információ &amp;raquo;.
        /// </summary>
        public static string Gen_LearnMore {
            get {
                return ResourceManager.GetString("Gen_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kipróbálom &amp;raquo;.
        /// </summary>
        public static string Gen_TryIt {
            get {
                return ResourceManager.GetString("Gen_TryIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cégünk jóárasított online vállalatirányítási megoldásokat kínál önnek..
        /// </summary>
        public static string HomeJumbo_Description {
            get {
                return ResourceManager.GetString("HomeJumbo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöljük a SeemplestCloud rendszerben!.
        /// </summary>
        public static string HomeJumbo_Title {
            get {
                return ResourceManager.GetString("HomeJumbo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string HomeMenu_Login {
            get {
                return ResourceManager.GetString("HomeMenu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string HomeMenu_Register {
            get {
                return ResourceManager.GetString("HomeMenu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 10 számla.
        /// </summary>
        public static string Package_Free_MaxInvoinces {
            get {
                return ResourceManager.GetString("Package_Free_MaxInvoinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 felhasználó.
        /// </summary>
        public static string Package_Free_MaxUser {
            get {
                return ResourceManager.GetString("Package_Free_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingyenes.
        /// </summary>
        public static string Package_Free_Price {
            get {
                return ResourceManager.GetString("Package_Free_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próbacsomag.
        /// </summary>
        public static string Package_Free_Title {
            get {
                return ResourceManager.GetString("Package_Free_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 200 számla.
        /// </summary>
        public static string Package_Micro_MaxInvoices {
            get {
                return ResourceManager.GetString("Package_Micro_MaxInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 felhasználó.
        /// </summary>
        public static string Package_Micro_MaxUser {
            get {
                return ResourceManager.GetString("Package_Micro_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 490 Ft/hó.
        /// </summary>
        public static string Package_Micro_Price {
            get {
                return ResourceManager.GetString("Package_Micro_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikró.
        /// </summary>
        public static string Package_Micro_Title {
            get {
                return ResourceManager.GetString("Package_Micro_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 2000 számla.
        /// </summary>
        public static string Package_Premium_MaxInvoices {
            get {
                return ResourceManager.GetString("Package_Premium_MaxInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 felhasználó.
        /// </summary>
        public static string Package_Premium_MaxUser {
            get {
                return ResourceManager.GetString("Package_Premium_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1790 Ft/hó.
        /// </summary>
        public static string Package_Premium_Price {
            get {
                return ResourceManager.GetString("Package_Premium_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prémium.
        /// </summary>
        public static string Package_Premium_Title {
            get {
                return ResourceManager.GetString("Package_Premium_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 500 számla.
        /// </summary>
        public static string Package_Small_MaxInvoices {
            get {
                return ResourceManager.GetString("Package_Small_MaxInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 felhasználó.
        /// </summary>
        public static string Package_Small_MaxUser {
            get {
                return ResourceManager.GetString("Package_Small_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 990 Ft/hó.
        /// </summary>
        public static string Package_Small_Price {
            get {
                return ResourceManager.GetString("Package_Small_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő.
        /// </summary>
        public static string Package_Small_Title {
            get {
                return ResourceManager.GetString("Package_Small_Title", resourceCulture);
            }
        }
    }
}
