//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeemplestCloud.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormsData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormsData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeemplestCloud.Resources.FormsData", typeof(FormsData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megerősítése.
        /// </summary>
        public static string General_ConfirmPassword {
            get {
                return ResourceManager.GetString("General_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó megerősítésének megadása kötelező.
        /// </summary>
        public static string General_ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("General_ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail cím.
        /// </summary>
        public static string General_Email {
            get {
                return ResourceManager.GetString("General_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott e-mail cím formája nem megfelelő.
        /// </summary>
        public static string General_Email_Error {
            get {
                return ResourceManager.GetString("General_Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az e-mail cím megadása kötelező.
        /// </summary>
        public static string General_Email_Required {
            get {
                return ResourceManager.GetString("General_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó hosszának 6 és 32 karakter között kell lennie.
        /// </summary>
        public static string General_Password_Error {
            get {
                return ResourceManager.GetString("General_Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó megadása kötelező.
        /// </summary>
        public static string General_Password_Required {
            get {
                return ResourceManager.GetString("General_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak és a megerősítésének egyeznie kell.
        /// </summary>
        public static string General_Passwords_DoNotMatch {
            get {
                return ResourceManager.GetString("General_Passwords_DoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        public static string General_Search {
            get {
                return ResourceManager.GetString("General_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak tartalmaznia kell kis- és nagybetűt, számjegyet és valamilyen egyéb írásjelet is.
        /// </summary>
        public static string General_StrongPassword {
            get {
                return ResourceManager.GetString("General_StrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználói név.
        /// </summary>
        public static string General_UserName {
            get {
                return ResourceManager.GetString("General_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A felhasználói név hosszának 2 és 32 között kell lennie.
        /// </summary>
        public static string General_UserName_Error {
            get {
                return ResourceManager.GetString("General_UserName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A felhasználó megjelenő neve.
        /// </summary>
        public static string General_UserName_Help {
            get {
                return ResourceManager.GetString("General_UserName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A felhasználói név megadása kötelező.
        /// </summary>
        public static string General_UserName_Required {
            get {
                return ResourceManager.GetString("General_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erre az e-mail címre megy a meghívó.
        /// </summary>
        public static string InviteUsers_InvitedEmailHelp {
            get {
                return ResourceManager.GetString("InviteUsers_InvitedEmailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez lesz a meghívott felhasználó neve.
        /// </summary>
        public static string InviteUsers_InvitedUserHelp {
            get {
                return ResourceManager.GetString("InviteUsers_InvitedUserHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév.
        /// </summary>
        public static string InviteUsers_InvitedUserName {
            get {
                return ResourceManager.GetString("InviteUsers_InvitedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új felhasználó meghívása.
        /// </summary>
        public static string InviteUsers_NewInvitation {
            get {
                return ResourceManager.GetString("InviteUsers_NewInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meghívás visszavonása.
        /// </summary>
        public static string InviteUsers_RevokeTooltip {
            get {
                return ResourceManager.GetString("InviteUsers_RevokeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elküldöm.
        /// </summary>
        public static string InviteUsers_SendButton {
            get {
                return ResourceManager.GetString("InviteUsers_SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maradjak bejelentkezve.
        /// </summary>
        public static string LoginViewModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginViewModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string SignUpViewModel_RegisterButton {
            get {
                return ResourceManager.GetString("SignUpViewModel_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az előfizetés neve.
        /// </summary>
        public static string SubscriptionPackageViewModel_SubscriptionName {
            get {
                return ResourceManager.GetString("SubscriptionPackageViewModel_SubscriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az előfizetés nevének megadása kötelező.
        /// </summary>
        public static string SubscriptionPackageViewModel_SubscriptionName_Required {
            get {
                return ResourceManager.GetString("SubscriptionPackageViewModel_SubscriptionName_Required", resourceCulture);
            }
        }
    }
}
