//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeemplestCloud.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeemplestCloud.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen bejelentkezés.
        /// </summary>
        public static string Error_InvalidLogin {
            get {
                return ResourceManager.GetString("Error_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        public static string Gen_Cancel {
            get {
                return ResourceManager.GetString("Gen_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előfizetek &amp;raquo;.
        /// </summary>
        public static string Gen_GetStarted {
            get {
                return ResourceManager.GetString("Gen_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to További információ &amp;raquo;.
        /// </summary>
        public static string Gen_LearnMore {
            get {
                return ResourceManager.GetString("Gen_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kipróbálom &amp;raquo;.
        /// </summary>
        public static string Gen_TryIt {
            get {
                return ResourceManager.GetString("Gen_TryIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cégünk jóárasított online vállalatirányítási megoldásokat kínál önnek..
        /// </summary>
        public static string HomeJumbo_Description {
            get {
                return ResourceManager.GetString("HomeJumbo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöljük a SeemplestCloud rendszerben!.
        /// </summary>
        public static string HomeJumbo_Title {
            get {
                return ResourceManager.GetString("HomeJumbo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string HomeMenu_Login {
            get {
                return ResourceManager.GetString("HomeMenu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feliratkozás.
        /// </summary>
        public static string HomeMenu_Register {
            get {
                return ResourceManager.GetString("HomeMenu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók meghívása.
        /// </summary>
        public static string InviteUsers_CurrentSpot {
            get {
                return ResourceManager.GetString("InviteUsers_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelentkezz be a SeemplestCloud szolgáltatásba!.
        /// </summary>
        public static string Login_CurrentSpot {
            get {
                return ResourceManager.GetString("Login_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés {0} azonosítással.
        /// </summary>
        public static string Login_NoAccount_CurrentSpot {
            get {
                return ResourceManager.GetString("Login_NoAccount_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahhoz, hogy bejelentkezve használatba tudja venni a rendszert, létre kell hoznia egy előfizetést is. Létre kívánja azt most hozni?.
        /// </summary>
        public static string Login_NoAccount_Explanation {
            get {
                return ResourceManager.GetString("Login_NoAccount_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs még {0} fiókjához előfizetése.
        /// </summary>
        public static string Login_NoAccount_Header {
            get {
                return ResourceManager.GetString("Login_NoAccount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem, most nem kívánom létrehozni.
        /// </summary>
        public static string Login_NoAccount_No {
            get {
                return ResourceManager.GetString("Login_NoAccount_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igen, létrehozom az előfizetést.
        /// </summary>
        public static string Login_NoAccount_Yes {
            get {
                return ResourceManager.GetString("Login_NoAccount_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feliratkozás új felhasználóként.
        /// </summary>
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés külső hitelesítési szolgáltatóval.
        /// </summary>
        public static string Login_Use_External {
            get {
                return ResourceManager.GetString("Login_Use_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés e-mail címmel és jelszóval.
        /// </summary>
        public static string Login_Use_Local {
            get {
                return ResourceManager.GetString("Login_Use_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók meghívása.
        /// </summary>
        public static string LoginMenu_InviteUsers {
            get {
                return ResourceManager.GetString("LoginMenu_InviteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók és jogosultságok.
        /// </summary>
        public static string LoginMenu_ManageRights {
            get {
                return ResourceManager.GetString("LoginMenu_ManageRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók és jogosultságaik.
        /// </summary>
        public static string ManageRights_CurrentSpot {
            get {
                return ResourceManager.GetString("ManageRights_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 10 számla.
        /// </summary>
        public static string Package_Free_MaxInvoinces {
            get {
                return ResourceManager.GetString("Package_Free_MaxInvoinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 felhasználó.
        /// </summary>
        public static string Package_Free_MaxUser {
            get {
                return ResourceManager.GetString("Package_Free_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingyenes.
        /// </summary>
        public static string Package_Free_Price {
            get {
                return ResourceManager.GetString("Package_Free_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próbacsomag.
        /// </summary>
        public static string Package_Free_Title {
            get {
                return ResourceManager.GetString("Package_Free_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 200 számla.
        /// </summary>
        public static string Package_Micro_MaxInvoices {
            get {
                return ResourceManager.GetString("Package_Micro_MaxInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 felhasználó.
        /// </summary>
        public static string Package_Micro_MaxUser {
            get {
                return ResourceManager.GetString("Package_Micro_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 490 Ft/hó.
        /// </summary>
        public static string Package_Micro_Price {
            get {
                return ResourceManager.GetString("Package_Micro_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikró.
        /// </summary>
        public static string Package_Micro_Title {
            get {
                return ResourceManager.GetString("Package_Micro_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 2000 számla.
        /// </summary>
        public static string Package_Premium_MaxInvoices {
            get {
                return ResourceManager.GetString("Package_Premium_MaxInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 felhasználó.
        /// </summary>
        public static string Package_Premium_MaxUser {
            get {
                return ResourceManager.GetString("Package_Premium_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1790 Ft/hó.
        /// </summary>
        public static string Package_Premium_Price {
            get {
                return ResourceManager.GetString("Package_Premium_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prémium.
        /// </summary>
        public static string Package_Premium_Title {
            get {
                return ResourceManager.GetString("Package_Premium_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. havi 500 számla.
        /// </summary>
        public static string Package_Small_MaxInvoices {
            get {
                return ResourceManager.GetString("Package_Small_MaxInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 felhasználó.
        /// </summary>
        public static string Package_Small_MaxUser {
            get {
                return ResourceManager.GetString("Package_Small_MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 990 Ft/hó.
        /// </summary>
        public static string Package_Small_Price {
            get {
                return ResourceManager.GetString("Package_Small_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő.
        /// </summary>
        public static string Package_Small_Title {
            get {
                return ResourceManager.GetString("Package_Small_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feliratkozás a SeemplestCloud szolgáltatásra.
        /// </summary>
        public static string SignUp_CurrentSpot {
            get {
                return ResourceManager.GetString("SignUp_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feliratkozás {0} azonosítással.
        /// </summary>
        public static string SignUp_External_CurrentSpot {
            get {
                return ResourceManager.GetString("SignUp_External_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add meg az &lt;strong&gt;e-mail címedet&lt;/strong&gt; és a &lt;strong&gt;felhasználói nevedet&lt;/strong&gt; a regisztrációhoz!.
        /// </summary>
        public static string SignUp_External_Description {
            get {
                return ResourceManager.GetString("SignUp_External_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztrálhatod magad az alábbi nyomógombokon jelölt külső hitelesítési szolgáltatókon keresztül. Ebben az esetben csak a felhasználói azonosítódat tároljuk, jelszavadat nem. A későbbiekben az itt használt hitelesítési szolgáltatón keresztül jelentkezhetsz be felhasználóként a rendszerbe..
        /// </summary>
        public static string SignUp_External_Explanation {
            get {
                return ResourceManager.GetString("SignUp_External_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SeemplestCloud szolgáltatások használatához regisztrálnod kell magad..
        /// </summary>
        public static string SignUp_FrontHeader {
            get {
                return ResourceManager.GetString("SignUp_FrontHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feliratkozás e-mail címmel és jelszóval.
        /// </summary>
        public static string SignUp_Internal_CurrentSpot {
            get {
                return ResourceManager.GetString("SignUp_Internal_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add meg az &lt;strong&gt;e-mail címedet&lt;/strong&gt;, &lt;strong&gt;felhasználói nevedet&lt;/strong&gt; és &lt;strong&gt;jelszavadat&lt;/strong&gt; a regisztrációhoz!.
        /// </summary>
        public static string SignUp_Internal_Description {
            get {
                return ResourceManager.GetString("SignUp_Internal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email címem és jelszavam megadásával iratkozom fel &amp;raquo;.
        /// </summary>
        public static string SignUp_Local_Button {
            get {
                return ResourceManager.GetString("SignUp_Local_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email címed és egy jelszó megadásával regisztrálhatod magad felhasználóként. Jelszavadat egyirányú titkosítással tároljuk, annak eredeti formáját nem ismerjük, és nem is tudjuk elérni. A későbbiekben ezzel a felhasználói információval kell bejelentkezned..
        /// </summary>
        public static string SignUp_Local_Description {
            get {
                return ResourceManager.GetString("SignUp_Local_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres feliratkozás.
        /// </summary>
        public static string SignUpConfirmation_CurrentSpot {
            get {
                return ResourceManager.GetString("SignUpConfirmation_CurrentSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres feliratkozásoddal nemcsak felhasználóként regisztráltunk a rendszerben, hanem egyúttal gazdája is vagy egy előfizetésnek, és a későbbiekben további felhasználókat is meghívhatsz. Adj nevet az előfizetésnek (ez most a regisztráció során megadott e-mail cím), és válaszd ki azt a csomagtípust, amellyel a szolgáltatást szeretnéd igénybe venni! Ezt a későbbiekben az éles használat során megváltoztathatod..
        /// </summary>
        public static string SignUpConfirmation_Message {
            get {
                return ResourceManager.GetString("SignUpConfirmation_Message", resourceCulture);
            }
        }
    }
}
