//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeemplestCloud.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeemplestCloud.Services.ServiceMessages", typeof(ServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott e-mail címet már meghívták felhasználónak..
        /// </summary>
        public static string EmailAlreadyInvited {
            get {
                return ResourceManager.GetString("EmailAlreadyInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott e-mail címet már foglalja egy felhasználó..
        /// </summary>
        public static string EmailReserved {
            get {
                return ResourceManager.GetString("EmailReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A felhasználó meghívásához tartozó kód érvénytelen. Lehet, hogy már lejárt, vagy a meghívást időközben visszavonták..
        /// </summary>
        public static string InvalidInvitationCode {
            get {
                return ResourceManager.GetString("InvalidInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen e-mail cím..
        /// </summary>
        public static string UnknownEmail {
            get {
                return ResourceManager.GetString("UnknownEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen meghívó azonosító.
        /// </summary>
        public static string UnknownInvitationId {
            get {
                return ResourceManager.GetString("UnknownInvitationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen felhasználói azonosító..
        /// </summary>
        public static string UnknownUserId {
            get {
                return ResourceManager.GetString("UnknownUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a felhasználói név már szerepel egy meghívón..
        /// </summary>
        public static string UserNameAlreadyInvited {
            get {
                return ResourceManager.GetString("UserNameAlreadyInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a felhasználói név már foglalt..
        /// </summary>
        public static string UserNameReserved {
            get {
                return ResourceManager.GetString("UserNameReserved", resourceCulture);
            }
        }
    }
}
