using System;
using Seemplest.Core.DataAccess.Attributes;
using Seemplest.Core.DataAccess.DataRecords;

namespace SeemplestCloud.Services.SubscriptionService.DataAccess
{
    // --- This class has been automatically generated from the database schema
    // --- 2014.10.07. 16:01:19
    [TableName("Subscription")]
    [SchemaName("Platform")]
    public class SubscriptionRecord : DataRecord<SubscriptionRecord>
    {
        private int _id;
        private string _subscriberName;
        private string _primaryEmail;
        private string _primaryPhone;
        private string _addrCountry;
        private string _addrZip;
        private string _addrTown;
        private string _addrLine1;
        private string _addrLine2;
        private string _addrState;
        private string _taxId;
        private string _bankAccountNo;
        private DateTimeOffset _createdUtc;
        private DateTimeOffset? _lastModifiedUtc;

        [PrimaryKey]
        [AutoGenerated]
        public int Id
        {
            get { return _id; }
            set { _id = Modify(value, "Id"); }
        }

        public string SubscriberName
        {
            get { return _subscriberName; }
            set { _subscriberName = Modify(value, "SubscriberName"); }
        }

        public string PrimaryEmail
        {
            get { return _primaryEmail; }
            set { _primaryEmail = Modify(value, "PrimaryEmail"); }
        }

        public string PrimaryPhone
        {
            get { return _primaryPhone; }
            set { _primaryPhone = Modify(value, "PrimaryPhone"); }
        }

        public string AddrCountry
        {
            get { return _addrCountry; }
            set { _addrCountry = Modify(value, "AddrCountry"); }
        }

        public string AddrZip
        {
            get { return _addrZip; }
            set { _addrZip = Modify(value, "AddrZip"); }
        }

        public string AddrTown
        {
            get { return _addrTown; }
            set { _addrTown = Modify(value, "AddrTown"); }
        }

        public string AddrLine1
        {
            get { return _addrLine1; }
            set { _addrLine1 = Modify(value, "AddrLine1"); }
        }

        public string AddrLine2
        {
            get { return _addrLine2; }
            set { _addrLine2 = Modify(value, "AddrLine2"); }
        }

        public string AddrState
        {
            get { return _addrState; }
            set { _addrState = Modify(value, "AddrState"); }
        }

        public string TaxId
        {
            get { return _taxId; }
            set { _taxId = Modify(value, "TaxId"); }
        }

        public string BankAccountNo
        {
            get { return _bankAccountNo; }
            set { _bankAccountNo = Modify(value, "BankAccountNo"); }
        }

        public DateTimeOffset CreatedUtc
        {
            get { return _createdUtc; }
            set { _createdUtc = Modify(value, "CreatedUtc"); }
        }

        public DateTimeOffset? LastModifiedUtc
        {
            get { return _lastModifiedUtc; }
            set { _lastModifiedUtc = Modify(value, "LastModifiedUtc"); }
        }
    }
}
